/************************************************************************************************
* Name      : FreshdeskTicketService
* Purpose   : Helper class to Account Trigger
* TestClass : FreshdeskTicketServiceTest
* Author    : Bruna Girão
* Date      : 11-07-2023
***************************************************************************************************/
public with sharing class FreshdeskTicketService {
    public FreshdeskTicketService() {

    }
}